
import { InventoryItem, ItemStatus, User, UserRole } from './types';

export const SYSTEM_BASES = [
  'Paka',
  'Lemal',
  'PD',
  'Pasir Gudang',
  'Connaught Bridge',
  'Generator',
  'Kapar'
];

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Alice Admin', username: 'admin', role: UserRole.ADMIN, base: 'HQ', email: 'alice@company.com', password: '12345' },
  { id: 'u2', name: 'Bob Staff', username: 'staff', role: UserRole.STAFF, base: 'Lemal', email: 'bob@company.com', password: '12345' },
  { id: 'u3', name: 'Charlie Storekeeper', username: 'storekeeper', role: UserRole.STOREKEEPER, base: 'Lemal', email: 'charlie@company.com', password: '12345' },
  { id: 'u4', name: 'David Staff', username: 'david', role: UserRole.STAFF, base: 'PD', email: 'david@company.com', password: '12345' },
  { id: 'u5', name: 'Eve Storekeeper', username: 'eve', role: UserRole.STOREKEEPER, base: 'PD', email: 'eve@company.com', password: '12345' },
  { id: 'u6', name: 'Frank Manager', username: 'manager', role: UserRole.BASE_MANAGER, base: 'Lemal', email: 'frank@company.com', password: '12345' },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: 'lml-001',
    no: '1',
    description: 'Impact Drill 18V LXT',
    maker: 'Makita',
    range: '0-2000 RPM',
    typeModel: 'DHP482Z',
    serialNo: 'MK-882910',
    unitPrice: '450.00',
    date: '12/01/2023',
    poNo: 'PO-23-LML-01',
    quantity: 1,
    assetNo: 'AST-LML-T01',
    location: 'Rack A-01',
    equipmentStatus: 'In Store',
    documentStatus: '-',
    dateOfQfRecorded: '-',
    hsemCategory: 'Power Tools',
    physicalStatus: 'Good',
    remarks: 'Battery checked ok',
    currentLocation: 'In Store',
    personInCharge: null,
    lastMovementDate: null,
    base: 'Lemal'
  },
  {
    id: 'lml-002',
    no: '2',
    description: 'Digital Multimeter',
    maker: 'Fluke',
    range: '1000V',
    typeModel: '179 True RMS',
    serialNo: 'FL-992834',
    unitPrice: '1200.00',
    date: '15/02/2023',
    poNo: 'PO-23-LML-02',
    quantity: 1,
    assetNo: 'AST-LML-I01',
    location: 'Cabinet C2',
    equipmentStatus: 'In Store',
    documentStatus: '-',
    dateOfQfRecorded: '-',
    hsemCategory: 'Instruments',
    physicalStatus: 'Good',
    remarks: 'Calibration due Dec 2024',
    currentLocation: 'In Store',
    personInCharge: null,
    lastMovementDate: null,
    base: 'Lemal'
  },
  {
    id: 'lml-003',
    no: '3',
    description: 'Safety Harness Full Body',
    maker: '3M',
    range: '100kg',
    typeModel: 'Protecta',
    serialNo: '3M-SH-771',
    unitPrice: '350.00',
    date: '10/03/2023',
    poNo: 'PO-23-LML-03',
    quantity: 1,
    assetNo: 'AST-LML-S01',
    location: 'Rack B-03',
    equipmentStatus: 'Borrowed by Bob Staff',
    documentStatus: '-',
    dateOfQfRecorded: '-',
    hsemCategory: 'PPE',
    physicalStatus: 'Good',
    remarks: 'Used for roof inspection',
    currentLocation: 'Project Site Alpha',
    personInCharge: 'Bob Staff',
    lastMovementDate: '2023-10-25',
    base: 'Lemal'
  },
  {
    id: 'lml-004',
    no: '4',
    description: 'Angle Grinder 4"',
    maker: 'Bosch',
    range: '720W',
    typeModel: 'GWS 7-100',
    serialNo: 'BS-GR-112',
    unitPrice: '280.00',
    date: '05/04/2023',
    poNo: 'PO-23-LML-04',
    quantity: 1,
    assetNo: 'AST-LML-T02',
    location: 'Rack A-02',
    equipmentStatus: 'In Store',
    documentStatus: '-',
    dateOfQfRecorded: '-',
    hsemCategory: 'Power Tools',
    physicalStatus: 'Switch Broken',
    remarks: 'Sent for repair 01/11',
    currentLocation: 'In Store',
    personInCharge: null,
    lastMovementDate: null,
    base: 'Lemal'
  },
  {
    id: 'lml-005',
    no: '5',
    description: 'Hydraulic Jack',
    maker: 'Masada',
    range: '10 Ton',
    typeModel: 'MH-10',
    serialNo: 'MS-HJ-009',
    unitPrice: '650.00',
    date: '20/05/2023',
    poNo: 'PO-23-LML-05',
    quantity: 1,
    assetNo: 'AST-LML-M01',
    location: 'Floor Area D',
    equipmentStatus: 'In Store',
    documentStatus: '-',
    dateOfQfRecorded: '-',
    hsemCategory: 'Machinery',
    physicalStatus: 'Scratched',
    remarks: 'Oil level checked',
    currentLocation: 'In Store',
    personInCharge: null,
    lastMovementDate: null,
    base: 'Lemal'
  },
  {
    id: 'lml-006',
    no: '6',
    description: 'Welding Set Inverter',
    maker: 'Lincoln Electric',
    range: '200A',
    typeModel: 'Invertec V205',
    serialNo: 'LE-WS-554',
    unitPrice: '3500.00',
    date: '12/06/2023',
    poNo: 'PO-23-LML-06',
    quantity: 1,
    assetNo: 'AST-LML-W01',
    location: 'Rack E-01',
    equipmentStatus: 'In Store',
    documentStatus: '-',
    dateOfQfRecorded: '-',
    hsemCategory: 'Welding',
    physicalStatus: 'Good',
    remarks: '',
    currentLocation: 'In Store',
    personInCharge: null,
    lastMovementDate: null,
    base: 'Lemal'
  }
];
